dirname: "/path/to/dir"
filename: "config.yaml"
gcp:
  project_id: "your-gcp-project-id"
aws:
  access_key_id: "your-aws-access-key-id"
  secret_access_key: "your-aws-secret-access-key"
azure:
  client_id: "your-azure-client-id"
  client_secret: "your-azure-client-secret"
  subscription_id: "your-azure-subscription-id"
db_config:
  username: "your-db-username"
  password: "your-db-password"
  database_name: "your-db-name"
  host: "your-db-host"
  port: "your-db-port"
api_config:
  port: 6000
  host: "localhost"
cognito_config:
  app_secret: "your-cognito-app-secret"
  client_id: "your-cognito-client-id"
