---
version: "3.1"
services:
  psql-db:
    image: postgres
    restart: always
    ports: [5432:5432]
    volumes: [/tmp/inariam/pg:/var/lib/postgresql/data]
    environment: [POSTGRES_PASSWORD=inariam]
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports: [8080:80]
    depends_on: [psql-db]
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  redis:
    image: redis
    ports: [6379:6379]
    volumes: [/tmp/inariam/redis:/data]
    restart: always
  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    ports: [8081:8081]
    depends_on: [redis]
    environment:
      REDIS_HOSTS: redis
  
  # core-app:
  #   build:
  #     context: ..
  #     dockerfile: scripts/Dockerfile
  #   depends_on:
  #     - psql-db
  #     - redis
  #   ports:
  #     - 8082:8082
# nextfront:
#     image: node:alpine
#     working_dir: /app
#     volumes:
#       - ./next-front:/app
#     ports:
#       - 3000:3000
