version: "3.1"

services:
  core-app:
    build:
      context: ../
      dockerfile: ./scripts/Dockerfile
    depends_on:
      - psql-db
      - redis
  psql-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=inariam
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    depends_on:
      - psql-db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  redis:
    image: redis
    restart: always

  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: redis

  # nextfront:
  #     image: node:alpine
  #     working_dir: /app
  #     volumes:
  #       - ./next-front:/app
  #     ports:
  #       - 3000:3000
